spring: 
  profiles:
     active: dev

---
server:
  port: 7001
#spring：的配置
spring:
  profiles:
  application:
    name: springcloud-config-eureka
 
  #Eureka配置
eureka:
  instance:
    hostname: localhost  #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向 Eureka注册中心注册自己
    fetch-registry: false  #fetch-registry如果为false ，则表示自己为注册中心
    service-url: #她是表示 监控页面~
      #单机： http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
---
server:
  port: 7001
#spring：的配置
spring:
  profiles: test
  application:
    name: springcloud-config-eureka
 
  #Eureka配置
eureka:
  instance:
    hostname: localhost  #Eureka服务端的实例名称
  client:
    register-with-eureka: false #表示是否向 Eureka注册中心注册自己
    fetch-registry: false  #fetch-registry如果为false ，则表示自己为注册中心
    service-url: #她是表示 监控页面~
      #单机： http://${eureka.instance.hostname}:${server.port}/eureka/
      defaultZone: http://localhost:7002/eureka/,http://localhost:7003/eureka/
